const 	HEIGHT 			= 600,
		WIDTH			= 800, 
		UP				= 0,
		RIGHT			= 1,
		DOWN			= 2,
		LEFT			= 3, 
		KEY_RIGHT_ARROW = 39,
		KEY_DOWN_ARROW 	= 40,
		KEY_LEFT_ARROW 	= 37,
		KEY_UP_ARROW 	= 38;
		KEY_ENTER = 13;
		KEY_ESC = 27;
		ACELERATION = 0;